export const lessonConfig = {
  id: 'er-pronunciation',
  title: '法语字母“er”发音课程',
  targetPhonemes: ['/e/', '/ɛr/'],
  coreSpellings: { '/e/': ['er'], '/ɛr/': ['er'] },
  ui: {
    optionAudio: true,
    submitRequired: true,
    shuffleOptions: true,
    speakingMode: 'fake',
    autoPlayExplanationVideo: false,
  },
  sequence: [
    {
      id: 'match-mer-vertu-parler',
      type: 'matching',
      prompt: '匹配发音及单词：',
      pairs: [
        { id: 'mer', word: 'mer', audio: 'mer' },
        { id: 'vertu', word: 'vertu', audio: 'vertu' },
        { id: 'parler', word: 'parler', audio: 'parler' },
      ],
      correctSound: 'correct-speak',
      shuffle: true,
    },
    {
      id: 'explain-er-rules',
      type: 'phoneme-explanation',
      grapheme: 'er',
      phoneme: '/e/、/ɛr/',
      explanation: '此处预留 er 发音规则视频，后续替换视频资源即可。',
      video: 'er-rules-video-placeholder',
    },
    {
      id: 'choose-fer',
      type: 'binary-pronunciation-choice',
      prompt: '选出下列单词正确的发音：',
      word: { text: 'fer', audio: 'fer' },
      options: [
        { id: 'fer-correct', audio: 'fer', label: '/fɛr/', correct: true },
        { id: 'fer-fe', audio: 'fer-distractor', label: '/fe/', correct: false },
      ],
      shuffleOptions: true,
      submitRequired: true,
      correctSound: 'correct-speak',
    },
    {
      id: 'choose-danser',
      type: 'binary-pronunciation-choice',
      prompt: '选出下列单词正确的发音：',
      word: { text: 'danser', audio: 'danser' },
      options: [
        { id: 'danser-correct', audio: 'danser', label: '/dɑ̃se/', correct: true },
        { id: 'danser-ending-er', audio: 'danser-distractor', label: '/dɑ̃sɛr/', correct: false },
      ],
      shuffleOptions: true,
      submitRequired: true,
      correctSound: 'correct-speak',
    },
    {
      id: 'choose-perdu',
      type: 'binary-pronunciation-choice',
      prompt: '选出下列单词正确的发音：',
      word: { text: 'perdu', audio: 'perdu' },
      options: [
        { id: 'perdu-correct', audio: 'perdu', label: '/pɛʁdy/', correct: true },
        { id: 'perdu-pedu', audio: 'perdu-distractor', label: '/pedu/', correct: false },
      ],
      shuffleOptions: true,
      submitRequired: true,
      correctSound: 'correct-speak',
    },
    { id: 'speak-ver', type: 'speaking-practice', word: 'ver', ipa: '/vɛr/', targetGrapheme: 'er', audio: 'ver' },
    { id: 'speak-habiter', type: 'speaking-practice', word: 'habiter', ipa: '/abite/', targetGrapheme: 'er', audio: 'habiter' },
    { id: 'speak-merci', type: 'speaking-practice', word: 'merci', ipa: '/mɛʁsi/', targetGrapheme: 'er', audio: 'merci' },
  ],
};
